
baseURL = "/"
title = "Theory of Taste"
languageCode = "en"
enableRobotsTXT = true

[params]
  description = "An essay by Pierre Vandenberghe"
  author = "Pierre Vandenberghe"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true
